#index:
#    path: /
#    controller: App\Controller\DefaultController::index

web:
  resource: '../src/Controller'
  type:     annotation
  prefix:   /
  trailing_slash_on_root: false
  options:
    utf8: true

api:
  resource: '../src/Controller/Api'
  type:     annotation
  prefix:   /api
  trailing_slash_on_root: false
